services:
  db:
    container_name: movie-recommendation-postgres-container
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME_DEV}
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
    ports:
      - "5432:5432"
    volumes:
      - movie-recommendation_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: movie-recommendation-sb-container
    image: movie-recommendation-sb-image:dev
    build:
      context: .
      dockerfile: src/Dockerfile.dev
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env

  frontend:
    container_name: movie-recommendation-nuxt-container
    image: movie-recommendation-nuxt-image:dev
    build:
      context: ./nuxt
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./nuxt:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network: