spring:
  application:
    name: movie-recommendation
  datasource:
    url: jdbc:postgresql://${POSTGRES_ENDPOINT_DEV}:${POSTGRES_PORT_DEV}/${POSTGRES_DATABASE_NAME_DEV}
    username: ${POSTGRES_USER_DEV}
    password: ${POSTGRES_PASSWORD_DEV}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    com.devtkms.devmatchapp: DEBUG
    org.apache.ibatis: DEBUG

tmdb:
  api:
    key: ${TMDB_API_KEY}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.devtkms.movierecommendation.typehandler

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}