spring:
  application:
    name: movie-recommendation
  datasource:
    url: jdbc:postgresql://${POSTGRES_ENDPOINT}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    com.devtkms.devmatchapp: DEBUG
    org.apache.ibatis: DEBUG
    com.devtkms.movierecommendation.security.JwtAuthenticationFilter: WARN

tmdb:
  api:
    key: ${TMDB_API_KEY}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.devtkms.movierecommendation.typehandler

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}