# Specify the base image
FROM node:22.9-alpine3.20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application source code
COPY . .

# Add Node.js binary path to the environment variable PATH
ENV PATH /app/node_modules/.bin:$PATH

# Start the application (temporarily commented out)
CMD ["npm", "run", "dev"]