# Build stage
FROM eclipse-temurin:21-jdk AS builder

# Set working directory
WORKDIR /app

# Set execute permission for Gradle wrapper
COPY ../gradlew .
COPY ../gradle ./gradle
RUN chmod +x gradlew

# Copy Gradle config files (to take advantage of Docker layer caching)
COPY ../build.gradle settings.gradle ./

# Download dependencies (using cache to speed up builds)
RUN ./gradlew dependencies --refresh-dependencies --no-daemon

# Copy all source code
COPY .. .

# Build the application (skip tests)
RUN ./gradlew clean build --refresh-dependencies -x test --no-daemon

# Runtime stage
FROM eclipse-temurin:21-jre

# Set working directory
WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=builder /app/build/libs/*.jar /movie-recommendation-sb.jar

# Set the entrypoint
ENTRYPOINT ["java", "-jar", "/movie-recommendation-sb.jar"]